version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
      - "10001:10001"
    environment:
      GRPC_PORT: 10000
      HTTP_PORT: 10001
      DB_CONNECTION: "dbname=shorter password=admin user=admin sslmode=disable host=postgres"
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: "shorter"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
