// Code generated by sqlc. DO NOT EDIT.
// source: createLink.sql

package db

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (short_link, original_link)
VALUES ($1, $2)
RETURNING short_link, original_link
`

type CreateLinkParams struct {
	ShortLink    string
	OriginalLink string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, createLink, arg.ShortLink, arg.OriginalLink)
	var i Link
	err := row.Scan(&i.ShortLink, &i.OriginalLink)
	return i, err
}
